- name: To Do App Playbook
  hosts: managed_nodes

  tasks:
    - name: Install Git and Python3
      become: yes
      ansible.builtin.yum:
        name: 
          - git
          - python3
        state: present