name: Continuous Integration
on:
  schedule:
    - cron: '35 0 * * *'
  push:
    paths-ignore:
        - 'README.md'
  pull_request:
    paths-ignore:
        - 'README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag my-test-image .
    - run: docker run --env-file .env.test  my-test-image
    - run: docker run --entrypoint poetry my-test-image run safety check

  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/exercise-12'
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build --target production --tag kallya21/todo-app:latest .
    - run: docker push kallya21/todo-app:latest
    - run: curl --fail -dH -X POST '${{ secrets.AZURE_WEBHOOK_URL }}'
   
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python-3.8@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}