name: Continuous Integration
on:
  push:
    paths-ignore:
        - 'README.md'
  pull_request:
    paths-ignore:
        - 'README.md' 

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker build --target test --tag my-test-image .
        docker run --env-file .env.test  my-test-image